apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: python-helloworld
      app.kubernetes.io/instance: python-helloworld
    name: python-helloworld
    namespace: python-sandbox
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30010
    selector:
      app.kubernetes.io/name: python-helloworld
    sessionAffinity: None
    type: NodPort
    