namespace:
  name: demo
 
service:
  port: 8111
  type: NodePort
  nodePort: 30009

image:
  repository: nginx 
  tag: alpine
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 50m
    memory: 256Mi

configmap:
  data: "version: alpine"
