apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-helloworld-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: project/helm/python-helloworld
    repoURL: https://github.com/callmatos/udacity-cloud-container-orchestration
    targetRevision: HEAD